manifest_version = 1

[module]
name = "Better embeds"
id = "better_embeds"
description = "A module improving various embeds."
version = "0.0.2"
license = "GNU GPLv3"
authors = ["Fripe"]
requirements=["aiohttp"]
